services:
  db:
    image: pgvector/pgvector:pg17
    container_name: efpg_db
    environment:
      POSTGRES_USER: postgre-user
      POSTGRES_PASSWORD: postgre-password
      POSTGRES_DB: test-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: